#
# (c) Copyright 2004 - 2015 Blue Pearl Software Inc.
# All rights reserved.
#
# This source code belongs to Blue Pearl Software Inc.
# It is considered trade secret and confidential, and is not to be used
# by parties who have not received written authorization
# from Blue Pearl Software Inc.
#
# Only authorized users are allowed to use, copy and modify
# this software provided that the above copyright notice
# remains in all copies of this software.
#
#
#
SET(BPS_QT_FOUND FALSE)
find_package(Qt5 REQUIRED COMPONENTS Core Network Sql Gui Widgets WebKit WebKitWidgets PrintSupport )

get_target_property(QtCore_location Qt5::Core LOCATION)
IF( EXISTS ${QtCore_location} )
	set(AUTOGEN_TARGETS_FOLDER "Generated Files")

    MESSAGE( STATUS "QtCore: ${QtCore_location}" )

    IF(WIN32)
        STRING(REGEX REPLACE "/bin.*" "" QTDIR_TMP ${QtCore_location})
    ELSE()
        STRING(REGEX REPLACE "/lib/libQ.*" "" QTDIR_TMP ${QtCore_location})
    ENDIF()
    
	SET( QT_VERSION_MAJOR ${Qt5Core_VERSION_MAJOR} )
	SET( QT_VERSION_MINOR ${Qt5Core_VERSION_MINOR} )
	SET( QT_VERSION_PATCH ${Qt5Core_VERSION_PATCH} )
				
    SET(QTDIR ${QTDIR_TMP} CACHE STRING "The QT Directory")
    message(STATUS "Looking in ${QTDIR} for QT shared library files.")
    SET(BPS_QT_FOUND TRUE)

    if ( WIN32 )
        IF( MSVC12 )
            STRING(REGEX REPLACE ".*/msvc" "msvc" MSVC_DIR ${QtCore_location})
            STRING(REGEX REPLACE "/bin.*" "" MSVC_DIR ${MSVC_DIR})
            IF(CMAKE_SIZEOF_VOID_P EQUAL 4) #32 bit
                IF( NOT ${MSVC_DIR} STREQUAL "msvc2013")
                    MESSAGE( STATUS "MSVC_DIR: ${MSVC_DIR}" )
                    MESSAGE( STATUS "Attempting to generate a Visual Studio Project for a 32 bit VS 2013" )
                    MESSAGE( STATUS "However, Qt is NOT pointing to a 32 bit VS 2013 area" )
                    MESSAGE( STATUS "If this is correct, please clear your CMake Cache and re-run cmake" )
                    MESSAGE( STATUS "Otherwise, please make sure your path is pointing to the correct qmake" )
                    MESSAGE( STATUS "Also, make sure to run cmake with -G \"Visual Studio 12 2013\" to set the correct 32 bit generator" )
                    MESSAGE( STATUS "If you want to generate a project for 64 bit, run cmake -G \"Visual Studio 12 2013 Win64\"" )
                    MESSAGE( FATAL_ERROR "See above for issues and solution" )
                ENDIF()
            ELSE()
                IF( NOT ${MSVC_DIR} STREQUAL "msvc2013_64")
                    MESSAGE( STATUS "MSVC_DIR: ${MSVC_DIR}" )
                    MESSAGE( STATUS "Attempting to generate a Visual Studio Project for a 64 bit VS 2013" )
                    MESSAGE( STATUS "However, Qt is NOT pointing to a 64 bit VS 2013 area" )
                    MESSAGE( STATUS "If this is correct, please clear your CMake Cache and re-run cmake" )
                    MESSAGE( STATUS "Otherwise, please make sure your path is pointing to the correct qmake" )
                    MESSAGE( STATUS "Also, make sure to run cmake with -G \"Visual Studio 12 2013 Win64\" to set the correct 64 bit generator" )
                    MESSAGE( STATUS "If you want to generate a project for 32 bit, run cmake -G \"Visual Studio 12 2013\"" )
                    MESSAGE( FATAL_ERROR "See above for issues and solution" )
                ENDIF()
            ENDIF()
        ENDIF()
    ENDIF()



	FUNCTION(AddQtIncludes ModuleName )
		if ( DEFINED Qt5${ModuleName}_INCLUDE_DIRS )
			foreach( dir ${Qt5${ModuleName}_INCLUDE_DIRS} )
				include_directories( ${dir} )
			endforeach()
		else()
			message( WARNING "Qt Module: ${ModuleName} is not defined (possibly not loaded)" )
		endif()
	ENDFUNCTION()

        MACRO(CheckFile isSet fileName )
                IF( NOT EXISTS ${fileName} )
                    message( FATAL_ERROR "Could not find Qt library ${fileName}" )
                ENDIF()
        ENDMACRO()


        MACRO(BPS_Install_Qt_libWin isSet libName )
            IF(${ARGN}) #negative logic
                IF( ${isSet} )
                    SET( INSTALL_IT FALSE )
                ELSE()
                    SET( INSTALL_IT TRUE )
                ENDIF()
            ELSE()
                SET( INSTALL_IT ${isSet} )
            ENDIF()
            IF( ${INSTALL_IT} )
                IF(WIN32)
                        message( STATUS "Installing Qt library ${libName}" )
                        install(PROGRAMS ${QTDIR}/bin/${libName}d.dll DESTINATION . CONFIGURATIONS Debug )
                        install(PROGRAMS ${QTDIR}/bin/${libName}d.pdb DESTINATION . CONFIGURATIONS Debug )
                        install(PROGRAMS ${QTDIR}/bin/${libName}.dll DESTINATION . CONFIGURATIONS RelWithDebInfo )

                        CheckFile( ${isSet} ${QTDIR}/bin/${libName}d.dll )
                        CheckFile( ${isSet} ${QTDIR}/bin/${libName}d.pdb )
                        CheckFile( ${isSet} ${QTDIR}/bin/${libName}.dll )
                ENDIF()
            ELSE()
                #message( STATUS "Skipping Installation of Qt library ${libName}" )
            ENDIF()
	ENDMACRO()

        MACRO(BPS_Install_Qt_libLinux  isSet libName )
            IF(${ARGN}) #negative logic
                IF( ${isSet} )
                    SET( INSTALL_IT FALSE )
                ELSE()
                    SET( INSTALL_IT TRUE )
                ENDIF()
            ELSE()
                SET( INSTALL_IT ${isSet} )
            ENDIF()
            IF( ${INSTALL_IT} )
                IF(NOT WIN32)
                        message( STATUS "Installing Qt library ${libName}" )
                        install(PROGRAMS ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH} DESTINATION lib )
                        install(PROGRAMS ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR}.${QT_VERSION_MINOR} DESTINATION lib )
                        install(PROGRAMS ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR} DESTINATION lib )

                        CheckFile( ${isSet} ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH} )
                        CheckFile( ${isSet} ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR}.${QT_VERSION_MINOR} )
                        CheckFile( ${isSet} ${QTDIR}/lib/lib${libName}.so.${QT_VERSION_MAJOR} )
		ENDIF()
            ELSE()
                #message( STATUS "Skipping Installation of Qt library ${libName}" )
	    ENDIF()
	ENDMACRO()

        MACRO(BPS_Install_Qt_lib  isSet libName )
            BPS_Install_Qt_libWin( ${isSet} ${libName} ${ARGN} )
            BPS_Install_Qt_libLinux( ${isSet} ${libName} ${ARGN} )
        ENDMACRO()

        MACRO(BPS_Install_Qt_pluginWin  isSet dir libName )
            IF(${ARGN}) #negative logic
                IF( ${isSet} )
                    SET( INSTALL_IT FALSE )
                ELSE()
                    SET( INSTALL_IT TRUE )
                ENDIF()
            ELSE()
                SET( INSTALL_IT ${isSet} )
            ENDIF()
            IF( ${INSTALL_IT} )
                IF(WIN32)
                        message( STATUS "Installing Qt plugin ${dir}/${libName}" )
                        install(PROGRAMS ${QTDIR}/plugins/${dir}/${libName}d.dll DESTINATION ${dir} CONFIGURATIONS Debug )
                        install(PROGRAMS ${QTDIR}/plugins/${dir}/${libName}d.pdb DESTINATION ${dir} CONFIGURATIONS Debug )
                        install(PROGRAMS ${QTDIR}/plugins/${dir}/${libName}.dll DESTINATION ${dir} CONFIGURATIONS RelWithDebInfo )

                        CheckFile( ${isSet} ${QTDIR}/plugins/${dir}/${libName}d.dll )
                        CheckFile( ${isSet} ${QTDIR}/plugins/${dir}/${libName}d.pdb )
                        CheckFile( ${isSet} ${QTDIR}/plugins/${dir}/${libName}.dll )
		ENDIF()
            ELSE()
                #message( STATUS "Skipping Installation of Qt plugin ${dir}/${libName}" )
	    ENDIF()
	ENDMACRO()

        MACRO(BPS_Install_Qt_pluginLinux  isSet dir libName )
            IF(${ARGN}) #negative logic
                IF( ${isSet} )
                    SET( INSTALL_IT FALSE )
                ELSE()
                    SET( INSTALL_IT TRUE )
                ENDIF()
            ELSE()
                SET( INSTALL_IT ${isSet} )
            ENDIF()
            IF( ${INSTALL_IT} )
                IF(NOT WIN32)
                        message( STATUS "Installing Qt library ${libName}" )
                        install(PROGRAMS ${QTDIR}/plugins/${dir}/lib${libName}.so DESTINATION ${dir} )

                        CheckFile( ${isSet} ${QTDIR}/plugins/${dir}/lib${libName}.so )
		ENDIF()
            ELSE()
                #message( STATUS "Skipping Installation of Qt plugin ${dir}/${libName}" )
	    ENDIF()
	ENDMACRO()

        MACRO(BPS_Install_Qt_plugin  isSet dir libName )
            BPS_Install_Qt_pluginWin( ${isSet} ${dir} ${libName} ${ARGN} )
            BPS_Install_Qt_pluginLinux( ${isSet} ${dir} ${libName} ${ARGN} )
        ENDMACRO()

        MACRO(BPS_Install_Qt_libX  isSet libName )
            IF(${ARGN}) #negative logic
                IF( ${isSet} )
                    SET( INSTALL_IT FALSE )
                ELSE()
                    SET( INSTALL_IT TRUE )
                ENDIF()
            ELSE()
                SET( INSTALL_IT ${isSet} )
            ENDIF()
            IF( ${INSTALL_IT} )
                IF(WIN32)
                        message( STATUS "Installing Qt library ${libName}" )
                        install(PROGRAMS ${QTDIR}/bin/${libName}.dll DESTINATION . )

                        CheckFile( ${isSet} ${QTDIR}/bin/${libName}.dll )
		ENDIF()
	    ENDIF()
	ENDMACRO()

        MACRO(BPS_Install_Qt)
                        BPS_Install_Qt_lib( QT_DONT_USE_QTCORE Qt5Core TRUE )
                        BPS_Install_Qt_lib( QT_DONT_USE_QTGUI Qt5Gui TRUE )
                        BPS_Install_Qt_lib( QT_DONT_USE_QTGUI Qt5Widgets TRUE )
                        BPS_Install_Qt_lib( QT_DONT_USE_QTGUI Qt5Sensors TRUE )
                        BPS_Install_Qt_lib( QT_DONT_USE_QTGUI Qt5PrintSupport TRUE )
                        BPS_Install_Qt_libX( QT_DONT_USE_QTGUI icudt54 TRUE )
                        BPS_Install_Qt_libX( QT_DONT_USE_QTGUI icuin54 TRUE )
                        BPS_Install_Qt_libX( QT_DONT_USE_QTGUI icuuc54 TRUE )
                        BPS_Install_Qt_libWin( QT_DONT_USE_QTGUI libEGL TRUE )
                        BPS_Install_Qt_libWin( QT_DONT_USE_QTGUI libGLESv2 TRUE )
                        BPS_Install_Qt_libLinux( QT_DONT_USE_QTGUI Qt5DBus TRUE )
                        BPS_Install_Qt_lib( QT_USE_XML_PATTERNS Qt5XmlPatterns )
                        BPS_Install_Qt_lib( QT_USE_XML Qt5Xml )
                        #BPS_Install_Qt_lib( QT_USE_QTDESIGNER Qt5Designer )
                        #BPS_Install_Qt_lib( QT_USE_QTDESIGNER Qt5DesignerComponents )
                        #BPS_Install_Qt_lib( QT_USE_QTMOTIF NotSupported )
                        BPS_Install_Qt_lib( QT_USE_QTMULTIMEDIA Qt5Multimedia )
                        BPS_Install_Qt_lib( QT_USE_QTNETWORK Qt5Network )
                        # BPS_Install_Qt_lib( QT_USE_QTNSPLUGIN NotSupported )
                        BPS_Install_Qt_lib( QT_USE_QTOPENGL Qt5OpenGL )
                        BPS_Install_Qt_lib( QT_USE_QTSQL Qt5Sql )
                        BPS_Install_Qt_lib( QT_USE_QTSVG Qt5Svg )
                        BPS_Install_Qt_lib( QT_USE_QTTEST Qt5Test )
                        #BPS_Install_Qt_lib( QT_USE_QTUITOOLS NotSupported )
                        #BPS_Install_Qt_lib( QT_USE_QTDBUS NotSupported )
                        BPS_Install_Qt_lib( QT_USE_QTSCRIPT Qt5Script )
                        #BPS_Install_Qt_lib( QT_USE_QTASSISTANTCLIENT NotSupported )
                        BPS_Install_Qt_lib( QT_USE_QTHELP Qt5Help )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5WebKit )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5WebKitWidgets )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5Multimedia )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5MultimediaWidgets )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5OpenGL )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5Positioning )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5Qml )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5Quick )
                        BPS_Install_Qt_lib( QT_USE_QTWEBKIT Qt5Quick )
                        #BPS_Install_Qt_lib( QT_USE_PHONON phonon )
                        BPS_Install_Qt_lib( QT_USE_QTSCRIPTTOOLS Qt5ScriptTools )
                        BPS_Install_Qt_lib( QT_USE_QTDECLARATIVE Qt5Declarative )
                        BPS_Install_Qt_pluginLinux( QT_DONT_USE_QTGUI platforms qxcb TRUE)
                        BPS_Install_Qt_pluginLinux( QT_DONT_USE_QTGUI platforms qminimal TRUE)
            if ( UNIX )
                if( ${BPS_REDHAT_RELEASE} VERSION_GREATER "6.0" )
                    BPS_Install_Qt_pluginLinux( QT_DONT_USE_QTGUI printsupport cupsprintersupport TRUE )
                ENDIF()
            ENDIF()
                        BPS_Install_Qt_pluginWin( QT_DONT_USE_QTGUI platforms qwindows TRUE)
                        BPS_Install_Qt_pluginWin( QT_DONT_USE_QTGUI platforms qminimal TRUE)
                        BPS_Install_Qt_pluginWin( QT_DONT_USE_QTGUI printsupport windowsprintersupport TRUE )
                        BPS_Install_Qt_pluginWin( QT_USE_QTSQL sqldrivers qsqlite)
        ENDMACRO()
ELSE()
    message( FATAL_ERROR "Could not find directory QtCore_location=${QtCore_location}" )
ENDIF()
